variables:
  BUILDER_VERSION: "2.1.0"
  BUILDER_COMPONENT: "builder"
  BUILDER_IMAGE: "$CI_REGISTRY_IMAGE/$BUILDER_COMPONENT:$BUILDER_VERSION"
  CARGO_HOME: "$CI_PROJECT_DIR/.cargo"

image: $BUILDER_IMAGE

cache:
  key:
    files:
      - Cargo.lock
  paths:
    - target/
    - $CARGO_HOME
  policy: pull

stages:
  - build
  - test
  - release
